# Use an official Python image from Docker Hub
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY app.py .

# Run the Python script
CMD ["python", "app.py"]